"""
Checkout session model.

Architecture note (Layer 6 - Action):
  A CheckoutSession is created ONLY after the user has explicitly approved a proposal.
  It represents the handoff to the merchant (e.g. Instacart) cart/checkout system.

  In production, checkout_url would be a real Instacart or merchant OAuth/cart URL.
  In this demo, it is a mock URL generated by the mock checkout service.

  The agent never receives payment credentials. The backend creates the checkout
  session and returns a URL for the user to complete payment in the merchant's UI.
"""

from datetime import datetime, timezone
from uuid import uuid4
from pydantic import BaseModel, Field


class CheckoutSession(BaseModel):
    checkout_session_id: str = Field(default_factory=lambda: f"chk_{uuid4().hex[:8]}")
    proposal_id: str
    merchant: str
    checkout_url: str
    status: str = "checkout_created"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    items_summary: str = ""
    estimated_total: float = 0.0
